[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LDPCDecoders = "3c486d74-64b9-4c60-8b1a-13a564e77efb"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PyQDecoders = "17f5de1a-9b79-4409-a58d-4d45812840f7"
Quantikz = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
